2024-04-29 07:29:19,043 - DFI => Execução iniciada
2024-04-29 07:29:19,087 -     => Main - Execução iniciada
2024-04-29 07:29:19,088 -     => balancasp6000 - Execução iniciada
2024-04-29 07:40:46,787 - DFI => Execução iniciada
2024-04-29 07:40:46,813 -     => Main - Execução iniciada
2024-04-29 07:40:46,814 -     => balancasp6000 - Execução iniciada
2024-04-29 07:44:35,516 - DFI => Execução iniciada
2024-04-29 07:44:35,542 -     => Main - Execução iniciada
2024-04-29 07:44:35,544 -     => avacorp - Execução iniciada
2024-04-29 08:04:51,088 -     => avacorp - Execução concluída
2024-04-29 08:04:51,089 -     => Main - Execução concluída
2024-04-29 08:05:19,189 - DFI => Execução iniciada
2024-04-29 08:05:19,214 -     => Main - Execução iniciada
2024-04-29 08:05:19,216 -     => commodities - Execução iniciada
2024-04-29 08:05:46,570 - DFI => Execução iniciada
2024-04-29 08:05:46,597 -     => Main - Execução iniciada
2024-04-29 08:05:46,598 -     => commodities - Execução iniciada
2024-04-29 08:07:30,099 - DFI => Execução iniciada
2024-04-29 08:07:30,125 -     => Main - Execução iniciada
2024-04-29 08:07:30,126 -     => commodities - Execução iniciada
2024-04-29 08:19:08,031 - DFI => Execução iniciada
2024-04-29 08:19:08,040 -     => Main - Execução iniciada
2024-04-29 08:19:08,040 -     => balancasp6000 - Execução iniciada
2024-04-29 08:19:08,402 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 08:19:08,422 -     => balancasp6000 - Execução concluída
2024-04-29 08:19:08,422 -     => Main - Execução concluída
2024-04-29 08:21:52,558 - DFI => Execução iniciada
2024-04-29 08:21:52,567 -     => Main - Execução iniciada
2024-04-29 08:21:52,568 -     => balancasp6000 - Execução iniciada
2024-04-29 08:21:52,893 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 08:21:52,920 -     => balancasp6000 - Execução concluída
2024-04-29 08:21:52,920 -     => Main - Execução concluída
2024-04-29 08:23:57,564 - DFI => Execução iniciada
2024-04-29 08:23:57,590 -     => Main - Execução iniciada
2024-04-29 08:23:57,591 -     => balancasp6000 - Execução iniciada
2024-04-29 08:28:23,406 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 08:28:26,014 -     => balancasp6000 - Execução concluída
2024-04-29 08:28:26,015 -     => Main - Execução concluída
2024-04-29 08:33:02,965 - DFI => Execução iniciada
2024-04-29 08:33:02,992 -     => Main - Execução iniciada
2024-04-29 08:33:02,993 -     => avacorp - Execução iniciada
2024-04-29 08:34:33,251 -       => Error:       (X) exportDataframeToDatabase.py.[exportDataframeToDatabase]: Erro ao exportar informações para o(s) database(s) de Destino:: 'NoneType' object has no attribute 'empty'
2024-04-29 08:42:35,715 - DFI => Execução iniciada
2024-04-29 08:42:35,742 -     => Main - Execução iniciada
2024-04-29 08:42:35,743 -     => avacorp - Execução iniciada
2024-04-29 08:42:39,948 - DFI => Execução iniciada
2024-04-29 08:42:39,975 -     => Main - Execução iniciada
2024-04-29 08:42:39,977 -     => avacorp - Execução iniciada
2024-04-29 08:49:42,525 - DFI => Execução iniciada
2024-04-29 08:49:42,552 -     => Main - Execução iniciada
2024-04-29 08:49:42,553 -     => avacorp - Execução iniciada
2024-04-29 09:04:26,530 -     => avacorp - Execução concluída
2024-04-29 09:04:26,542 -     => Main - Execução concluída
2024-04-29 09:04:52,261 - DFI => Execução iniciada
2024-04-29 09:04:52,289 -     => Main - Execução iniciada
2024-04-29 09:04:52,290 -     => commodities - Execução iniciada
2024-04-29 09:07:13,927 - DFI => Execução iniciada
2024-04-29 09:07:13,953 -     => Main - Execução iniciada
2024-04-29 09:07:13,954 -     => commodities - Execução iniciada
2024-04-29 09:08:39,127 - DFI => Execução iniciada
2024-04-29 09:08:39,154 -     => Main - Execução iniciada
2024-04-29 09:08:39,155 -     => commodities - Execução iniciada
2024-04-29 09:19:37,435 - DFI => Execução iniciada
2024-04-29 09:19:37,462 -     => Main - Execução iniciada
2024-04-29 09:19:37,463 -     => balancasp6000 - Execução iniciada
2024-04-29 09:22:03,274 - DFI => Execução iniciada
2024-04-29 09:22:03,300 -     => Main - Execução iniciada
2024-04-29 09:22:03,301 -     => balancasp6000 - Execução iniciada
2024-04-29 09:24:13,014 - DFI => Execução iniciada
2024-04-29 09:24:13,040 -     => Main - Execução iniciada
2024-04-29 09:24:13,041 -     => balancasp6000 - Execução iniciada
2024-04-29 09:24:24,491 -       => Error:       (X) exportDataframeToTxt.py.[exportDataframeToTxt]: Exportando informações:: 'dict' object has no attribute 'get_programName'
2024-04-29 09:26:34,853 - DFI => Execução iniciada
2024-04-29 09:26:34,879 -     => Main - Execução iniciada
2024-04-29 09:26:34,880 -     => avacorp - Execução iniciada
2024-04-29 09:29:03,518 - DFI => Execução iniciada
2024-04-29 09:29:03,546 -     => Main - Execução iniciada
2024-04-29 09:29:03,547 -     => avacorp - Execução iniciada
2024-04-29 09:29:29,973 - DFI => Execução iniciada
2024-04-29 09:29:29,999 -     => Main - Execução iniciada
2024-04-29 09:29:30,000 -     => balancasp6000 - Execução iniciada
2024-04-29 09:32:41,288 - DFI => Execução iniciada
2024-04-29 09:32:41,297 -     => Main - Execução iniciada
2024-04-29 09:32:41,297 -     => balancasp6000 - Execução iniciada
2024-04-29 09:32:43,375 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 09:32:43,376 -       => Error:       (X) exportDataframeToTxt.py.[exportDataframeToTxt]: Exportando informações:: name 'sheet' is not defined
2024-04-29 09:35:07,665 - DFI => Execução iniciada
2024-04-29 09:35:07,673 -     => Main - Execução iniciada
2024-04-29 09:35:07,673 -     => balancasp6000 - Execução iniciada
2024-04-29 09:35:08,144 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 09:35:08,256 -     => balancasp6000 - Execução concluída
2024-04-29 09:35:08,256 -     => Main - Execução concluída
2024-04-29 09:36:12,511 - DFI => Execução iniciada
2024-04-29 09:36:12,537 -     => Main - Execução iniciada
2024-04-29 09:36:12,538 -     => balancasp6000 - Execução iniciada
2024-04-29 09:39:43,557 - DFI => Execução iniciada
2024-04-29 09:39:43,565 -     => Main - Execução iniciada
2024-04-29 09:39:43,566 -     => balancasp6000 - Execução iniciada
2024-04-29 09:39:43,880 -     => balancasp6000 - Execução concluída
2024-04-29 09:39:43,880 -     => Main - Execução concluída
2024-04-29 09:41:43,953 -     => Main - Execução iniciada
2024-04-29 09:41:43,954 -     => balancasp6000 - Execução iniciada
2024-04-29 09:41:44,127 -     => balancasp6000 - Execução concluída
2024-04-29 09:41:44,127 -     => Main - Execução concluída
2024-04-29 09:43:44,211 -     => Main - Execução iniciada
2024-04-29 09:43:44,211 -     => balancasp6000 - Execução iniciada
2024-04-29 09:43:44,373 -     => balancasp6000 - Execução concluída
2024-04-29 09:43:44,374 -     => Main - Execução concluída
2024-04-29 09:45:44,440 -     => Main - Execução iniciada
2024-04-29 09:45:44,441 -     => balancasp6000 - Execução iniciada
2024-04-29 09:45:44,726 -     => balancasp6000 - Execução concluída
2024-04-29 09:45:44,727 -     => Main - Execução concluída
2024-04-29 09:47:44,798 -     => Main - Execução iniciada
2024-04-29 09:47:44,798 -     => balancasp6000 - Execução iniciada
2024-04-29 09:47:44,987 -     => balancasp6000 - Execução concluída
2024-04-29 09:47:44,987 -     => Main - Execução concluída
2024-04-29 09:49:45,065 -     => Main - Execução iniciada
2024-04-29 09:49:45,066 -     => balancasp6000 - Execução iniciada
2024-04-29 09:49:45,242 -     => balancasp6000 - Execução concluída
2024-04-29 09:49:45,242 -     => Main - Execução concluída
2024-04-29 09:51:45,314 -     => Main - Execução iniciada
2024-04-29 09:51:45,314 -     => balancasp6000 - Execução iniciada
2024-04-29 09:51:45,524 -     => balancasp6000 - Execução concluída
2024-04-29 09:51:45,524 -     => Main - Execução concluída
2024-04-29 09:53:45,591 -     => Main - Execução iniciada
2024-04-29 09:53:45,592 -     => balancasp6000 - Execução iniciada
2024-04-29 09:53:45,774 -     => balancasp6000 - Execução concluída
2024-04-29 09:53:45,774 -     => Main - Execução concluída
2024-04-29 09:55:45,850 -     => Main - Execução iniciada
2024-04-29 09:55:45,850 -     => balancasp6000 - Execução iniciada
2024-04-29 09:55:46,012 -     => balancasp6000 - Execução concluída
2024-04-29 09:55:46,013 -     => Main - Execução concluída
2024-04-29 09:57:46,087 -     => Main - Execução iniciada
2024-04-29 09:57:46,087 -     => balancasp6000 - Execução iniciada
2024-04-29 09:57:46,260 -     => balancasp6000 - Execução concluída
2024-04-29 09:57:46,260 -     => Main - Execução concluída
2024-04-29 09:59:46,336 -     => Main - Execução iniciada
2024-04-29 09:59:46,337 -     => balancasp6000 - Execução iniciada
2024-04-29 09:59:46,575 -     => balancasp6000 - Execução concluída
2024-04-29 09:59:46,575 -     => Main - Execução concluída
2024-04-29 10:01:46,642 -     => Main - Execução iniciada
2024-04-29 10:01:46,643 -     => balancasp6000 - Execução iniciada
2024-04-29 10:01:46,972 -     => balancasp6000 - Execução concluída
2024-04-29 10:01:46,972 -     => Main - Execução concluída
2024-04-29 10:03:47,046 -     => Main - Execução iniciada
2024-04-29 10:03:47,046 -     => balancasp6000 - Execução iniciada
2024-04-29 10:03:47,308 -     => balancasp6000 - Execução concluída
2024-04-29 10:03:47,308 -     => Main - Execução concluída
2024-04-29 10:05:47,377 -     => Main - Execução iniciada
2024-04-29 10:05:47,378 -     => balancasp6000 - Execução iniciada
2024-04-29 10:05:47,525 -     => balancasp6000 - Execução concluída
2024-04-29 10:05:47,525 -     => Main - Execução concluída
2024-04-29 10:07:47,596 -     => Main - Execução iniciada
2024-04-29 10:07:47,596 -     => balancasp6000 - Execução iniciada
2024-04-29 10:07:47,758 -     => balancasp6000 - Execução concluída
2024-04-29 10:07:47,759 -     => Main - Execução concluída
2024-04-29 10:09:47,827 -     => Main - Execução iniciada
2024-04-29 10:09:47,827 -     => balancasp6000 - Execução iniciada
2024-04-29 10:09:47,973 -     => balancasp6000 - Execução concluída
2024-04-29 10:09:47,973 -     => Main - Execução concluída
2024-04-29 10:11:48,061 -     => Main - Execução iniciada
2024-04-29 10:11:48,062 -     => balancasp6000 - Execução iniciada
2024-04-29 10:11:48,365 -     => balancasp6000 - Execução concluída
2024-04-29 10:11:48,365 -     => Main - Execução concluída
2024-04-29 10:13:48,439 -     => Main - Execução iniciada
2024-04-29 10:13:48,439 -     => balancasp6000 - Execução iniciada
2024-04-29 10:13:48,599 -     => balancasp6000 - Execução concluída
2024-04-29 10:13:48,599 -     => Main - Execução concluída
2024-04-29 10:15:48,672 -     => Main - Execução iniciada
2024-04-29 10:15:48,672 -     => balancasp6000 - Execução iniciada
2024-04-29 10:15:48,836 -     => balancasp6000 - Execução concluída
2024-04-29 10:15:48,836 -     => Main - Execução concluída
2024-04-29 10:17:48,909 -     => Main - Execução iniciada
2024-04-29 10:17:48,909 -     => balancasp6000 - Execução iniciada
2024-04-29 10:17:49,050 -     => balancasp6000 - Execução concluída
2024-04-29 10:17:49,050 -     => Main - Execução concluída
2024-04-29 10:19:49,124 -     => Main - Execução iniciada
2024-04-29 10:19:49,124 -     => balancasp6000 - Execução iniciada
2024-04-29 10:19:49,335 -     => balancasp6000 - Execução concluída
2024-04-29 10:19:49,335 -     => Main - Execução concluída
2024-04-29 10:21:49,406 -     => Main - Execução iniciada
2024-04-29 10:21:49,407 -     => balancasp6000 - Execução iniciada
2024-04-29 10:21:49,579 -     => balancasp6000 - Execução concluída
2024-04-29 10:21:49,579 -     => Main - Execução concluída
2024-04-29 10:23:49,653 -     => Main - Execução iniciada
2024-04-29 10:23:49,654 -     => balancasp6000 - Execução iniciada
2024-04-29 10:23:49,811 -     => balancasp6000 - Execução concluída
2024-04-29 10:23:49,812 -     => Main - Execução concluída
2024-04-29 10:25:49,881 -     => Main - Execução iniciada
2024-04-29 10:25:49,881 -     => balancasp6000 - Execução iniciada
2024-04-29 10:25:50,224 -     => balancasp6000 - Execução concluída
2024-04-29 10:25:50,225 -     => Main - Execução concluída
2024-04-29 10:27:50,291 -     => Main - Execução iniciada
2024-04-29 10:27:50,291 -     => balancasp6000 - Execução iniciada
2024-04-29 10:27:50,449 -     => balancasp6000 - Execução concluída
2024-04-29 10:27:50,449 -     => Main - Execução concluída
2024-04-29 10:29:50,569 -     => Main - Execução iniciada
2024-04-29 10:29:50,569 -     => balancasp6000 - Execução iniciada
2024-04-29 10:29:50,728 -     => balancasp6000 - Execução concluída
2024-04-29 10:29:50,728 -     => Main - Execução concluída
2024-04-29 10:31:50,797 -     => Main - Execução iniciada
2024-04-29 10:31:50,798 -     => balancasp6000 - Execução iniciada
2024-04-29 10:31:50,997 -     => balancasp6000 - Execução concluída
2024-04-29 10:31:50,997 -     => Main - Execução concluída
2024-04-29 10:33:51,070 -     => Main - Execução iniciada
2024-04-29 10:33:51,070 -     => balancasp6000 - Execução iniciada
2024-04-29 10:33:51,257 -     => balancasp6000 - Execução concluída
2024-04-29 10:33:51,257 -     => Main - Execução concluída
2024-04-29 10:35:51,335 -     => Main - Execução iniciada
2024-04-29 10:35:51,335 -     => balancasp6000 - Execução iniciada
2024-04-29 10:35:51,849 -     => balancasp6000 - Execução concluída
2024-04-29 10:35:51,849 -     => Main - Execução concluída
2024-04-29 10:37:51,919 -     => Main - Execução iniciada
2024-04-29 10:37:51,920 -     => balancasp6000 - Execução iniciada
2024-04-29 10:37:52,084 -     => balancasp6000 - Execução concluída
2024-04-29 10:37:52,085 -     => Main - Execução concluída
2024-04-29 10:39:52,170 -     => Main - Execução iniciada
2024-04-29 10:39:52,170 -     => balancasp6000 - Execução iniciada
2024-04-29 10:39:52,371 -     => balancasp6000 - Execução concluída
2024-04-29 10:39:52,371 -     => Main - Execução concluída
2024-04-29 10:41:52,439 -     => Main - Execução iniciada
2024-04-29 10:41:52,439 -     => balancasp6000 - Execução iniciada
2024-04-29 10:41:52,612 -     => balancasp6000 - Execução concluída
2024-04-29 10:41:52,612 -     => Main - Execução concluída
2024-04-29 10:43:52,681 -     => Main - Execução iniciada
2024-04-29 10:43:52,682 -     => balancasp6000 - Execução iniciada
2024-04-29 10:43:52,912 -     => balancasp6000 - Execução concluída
2024-04-29 10:43:52,912 -     => Main - Execução concluída
2024-04-29 10:45:52,982 -     => Main - Execução iniciada
2024-04-29 10:45:52,983 -     => balancasp6000 - Execução iniciada
2024-04-29 10:45:53,368 -     => balancasp6000 - Execução concluída
2024-04-29 10:45:53,368 -     => Main - Execução concluída
2024-04-29 10:47:53,459 -     => Main - Execução iniciada
2024-04-29 10:47:53,460 -     => balancasp6000 - Execução iniciada
2024-04-29 10:47:53,628 -     => balancasp6000 - Execução concluída
2024-04-29 10:47:53,628 -     => Main - Execução concluída
2024-04-29 10:49:53,713 -     => Main - Execução iniciada
2024-04-29 10:49:53,714 -     => balancasp6000 - Execução iniciada
2024-04-29 10:49:53,998 -     => balancasp6000 - Execução concluída
2024-04-29 10:49:53,999 -     => Main - Execução concluída
2024-04-29 10:51:54,064 -     => Main - Execução iniciada
2024-04-29 10:51:54,064 -     => balancasp6000 - Execução iniciada
2024-04-29 10:51:54,220 -     => balancasp6000 - Execução concluída
2024-04-29 10:51:54,220 -     => Main - Execução concluída
2024-04-29 10:52:39,227 - DFI => Execução iniciada
2024-04-29 10:52:39,257 -     => Main - Execução iniciada
2024-04-29 10:52:39,259 -     => balancasp6000 - Execução iniciada
2024-04-29 10:55:10,381 - DFI => Execução iniciada
2024-04-29 10:55:10,408 -     => Main - Execução iniciada
2024-04-29 10:55:10,409 -     => balancasp6000 - Execução iniciada
2024-04-29 10:55:49,822 - DFI => Execução iniciada
2024-04-29 10:55:49,847 -     => Main - Execução iniciada
2024-04-29 10:55:49,849 -     => balancasp6000 - Execução iniciada
2024-04-29 10:59:01,184 - DFI => Execução iniciada
2024-04-29 10:59:01,211 -     => Main - Execução iniciada
2024-04-29 10:59:01,212 -     => balancasp6000 - Execução iniciada
2024-04-29 11:03:00,600 - DFI => Execução iniciada
2024-04-29 11:03:00,627 -     => Main - Execução iniciada
2024-04-29 11:03:00,628 -     => balancasp6000 - Execução iniciada
2024-04-29 11:03:19,761 -     => balancasp6000 - Execução concluída
2024-04-29 11:03:19,761 -     => Main - Execução concluída
2024-04-29 11:04:11,432 - DFI => Execução iniciada
2024-04-29 11:04:11,441 -     => Main - Execução iniciada
2024-04-29 11:04:11,441 -     => balancasp6000 - Execução iniciada
2024-04-29 11:04:11,747 -       => Error:       (X) importTxtToDataframe.py.[executeImportTxtToDataframe]: Executando importação de arquivo:: No columns to parse from file
2024-04-29 11:05:03,335 - DFI => Execução iniciada
2024-04-29 11:05:03,344 -     => Main - Execução iniciada
2024-04-29 11:05:03,345 -     => balancasp6000 - Execução iniciada
2024-04-29 11:05:03,660 -     => balancasp6000 - Execução concluída
2024-04-29 11:05:03,660 -     => Main - Execução concluída
2024-04-29 11:07:03,728 -     => Main - Execução iniciada
2024-04-29 11:07:03,728 -     => balancasp6000 - Execução iniciada
2024-04-29 11:07:03,922 -       => Error:       (X) importTxtToDataframe.py.[executeImportTxtToDataframe]: Executando importação de arquivo:: No columns to parse from file
2024-04-29 11:07:37,619 - DFI => Execução iniciada
2024-04-29 11:07:37,627 -     => Main - Execução iniciada
2024-04-29 11:07:37,627 -     => balancasp6000 - Execução iniciada
2024-04-29 11:07:37,944 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 11:07:37,969 -     => balancasp6000 - Execução concluída
2024-04-29 11:07:37,969 -     => Main - Execução concluída
2024-04-29 11:09:44,469 - DFI => Execução iniciada
2024-04-29 11:09:44,478 -     => Main - Execução iniciada
2024-04-29 11:09:44,478 -     => balancasp6000 - Execução iniciada
2024-04-29 11:09:44,855 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 11:09:44,880 -     => balancasp6000 - Execução concluída
2024-04-29 11:09:44,880 -     => Main - Execução concluída
2024-04-29 11:10:46,213 - DFI => Execução iniciada
2024-04-29 11:10:46,238 -     => Main - Execução iniciada
2024-04-29 11:10:46,239 -     => balancasp6000 - Execução iniciada
2024-04-29 11:11:07,141 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 11:11:07,230 -     => balancasp6000 - Execução concluída
2024-04-29 11:11:07,231 -     => Main - Execução concluída
2024-04-29 11:11:47,561 - DFI => Execução iniciada
2024-04-29 11:11:47,587 -     => Main - Execução iniciada
2024-04-29 11:11:47,588 -     => balancasp6000 - Execução iniciada
2024-04-29 11:17:40,612 - DFI => Execução iniciada
2024-04-29 11:17:40,638 -     => Main - Execução iniciada
2024-04-29 11:17:40,640 -     => balancasp6000 - Execução iniciada
2024-04-29 11:19:52,581 - DFI => Execução iniciada
2024-04-29 11:19:52,607 -     => Main - Execução iniciada
2024-04-29 11:19:52,608 -     => balancasp6000 - Execução iniciada
2024-04-29 11:26:15,707 - DFI => Execução iniciada
2024-04-29 11:26:15,734 -     => Main - Execução iniciada
2024-04-29 11:26:15,735 -     => balancasp6000 - Execução iniciada
2024-04-29 11:27:47,069 - DFI => Execução iniciada
2024-04-29 11:27:47,094 -     => Main - Execução iniciada
2024-04-29 11:27:47,095 -     => balancasp6000 - Execução iniciada
2024-04-29 11:38:00,444 - DFI => Execução iniciada
2024-04-29 11:38:00,471 -     => Main - Execução iniciada
2024-04-29 11:38:00,472 -     => balancasp6000 - Execução iniciada
2024-04-29 11:51:35,217 - DFI => Execução iniciada
2024-04-29 11:51:35,243 -     => Main - Execução iniciada
2024-04-29 11:51:35,244 -     => balancasp6000 - Execução iniciada
2024-04-29 11:51:38,006 -       => Error:       (X) updateDataframe.py.[updateDataframe]: Update dos dataframes:: You are trying to merge on object and int64 columns for key 'sp6000_cenario'. If you wish to proceed you should use pd.concat
2024-04-29 11:52:25,126 - DFI => Execução iniciada
2024-04-29 11:52:25,151 -     => Main - Execução iniciada
2024-04-29 11:52:25,153 -     => balancasp6000 - Execução iniciada
2024-04-29 11:53:21,783 -       => Error:       (X) updateDataframe.py.[updateDataframe]: Update dos dataframes:: You are trying to merge on object and int64 columns for key 'sp6000_cenario'. If you wish to proceed you should use pd.concat
2024-04-29 11:58:19,522 - DFI => Execução iniciada
2024-04-29 11:58:19,549 -     => Main - Execução iniciada
2024-04-29 11:58:19,550 -     => balancasp6000 - Execução iniciada
2024-04-29 11:58:54,749 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 11:58:54,796 -     => balancasp6000 - Execução concluída
2024-04-29 11:58:54,796 -     => Main - Execução concluída
2024-04-29 11:59:05,589 - DFI => Execução iniciada
2024-04-29 11:59:05,598 -     => Main - Execução iniciada
2024-04-29 11:59:05,598 -     => balancasp6000 - Execução iniciada
2024-04-29 11:59:05,833 -       => Error:       (X) importTxtToDataframe.py.[executeImportTxtToDataframe]: Executando importação de arquivo:: No columns to parse from file
2024-04-29 12:11:54,200 - DFI => Execução iniciada
2024-04-29 12:11:54,226 -     => Main - Execução iniciada
2024-04-29 12:11:54,227 -     => balancasp6000 - Execução iniciada
2024-04-29 12:11:54,631 -       => Error:       (X) importTxtToDataframe.py.[executeImportTxtToDataframe]: Executando importação de arquivo:: No columns to parse from file
2024-04-29 12:12:23,618 - DFI => Execução iniciada
2024-04-29 12:12:23,645 -     => Main - Execução iniciada
2024-04-29 12:12:23,646 -     => balancasp6000 - Execução iniciada
2024-04-29 12:12:31,855 -       => Error:       (X) importTxtToDataframe.py.[executeImportTxtToDataframe]: Executando importação de arquivo:: No columns to parse from file
2024-04-29 12:17:00,425 - DFI => Execução iniciada
2024-04-29 12:17:00,452 -     => Main - Execução iniciada
2024-04-29 12:17:00,452 -     => balancasp6000 - Execução iniciada
2024-04-29 12:17:19,301 -       => Error:       (X) updateDataframe.py.[updateDataframe]: Update dos dataframes:: 'NoneType' object has no attribute 'columns'
2024-04-29 12:17:46,501 - DFI => Execução iniciada
2024-04-29 12:17:46,529 -     => Main - Execução iniciada
2024-04-29 12:17:46,530 -     => balancasp6000 - Execução iniciada
2024-04-29 12:18:04,356 -       => Error:       (X) updateDataframe.py.[updateDataframe]: Update dos dataframes:: 'NoneType' object has no attribute 'columns'
2024-04-29 12:18:18,296 - DFI => Execução iniciada
2024-04-29 12:18:18,323 -     => Main - Execução iniciada
2024-04-29 12:18:18,324 -     => balancasp6000 - Execução iniciada
2024-04-29 12:18:30,593 -       => Error:       (X) updateDataframe.py.[updateDataframe]: Update dos dataframes:: 'NoneType' object has no attribute 'columns'
2024-04-29 12:18:40,742 - DFI => Execução iniciada
2024-04-29 12:18:40,768 -     => Main - Execução iniciada
2024-04-29 12:18:40,769 -     => balancasp6000 - Execução iniciada
2024-04-29 12:21:54,381 - DFI => Execução iniciada
2024-04-29 12:21:54,407 -     => Main - Execução iniciada
2024-04-29 12:21:54,408 -     => balancasp6000 - Execução iniciada
2024-04-29 12:23:11,634 - DFI => Execução iniciada
2024-04-29 12:23:11,660 -     => Main - Execução iniciada
2024-04-29 12:23:11,661 -     => balancasp6000 - Execução iniciada
2024-04-29 12:26:03,276 - DFI => Execução iniciada
2024-04-29 12:26:03,302 -     => Main - Execução iniciada
2024-04-29 12:26:03,303 -     => balancasp6000 - Execução iniciada
2024-04-29 12:26:40,700 - DFI => Execução iniciada
2024-04-29 12:26:40,708 -     => Main - Execução iniciada
2024-04-29 12:26:40,709 -     => balancasp6000 - Execução iniciada
2024-04-29 12:26:41,091 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 12:26:41,122 -     => balancasp6000 - Execução concluída
2024-04-29 12:26:41,122 -     => Main - Execução concluída
2024-04-29 12:26:46,468 - DFI => Execução iniciada
2024-04-29 12:26:46,478 -     => Main - Execução iniciada
2024-04-29 12:26:46,478 -     => balancasp6000 - Execução iniciada
2024-04-29 12:26:46,794 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 12:26:46,825 -     => balancasp6000 - Execução concluída
2024-04-29 12:26:46,826 -     => Main - Execução concluída
2024-04-29 12:52:40,428 - DFI => Execução iniciada
2024-04-29 12:52:40,441 -     => Main - Execução iniciada
2024-04-29 12:52:40,441 -     => commodities - Execução iniciada
2024-04-29 12:53:29,716 - DFI => Execução iniciada
2024-04-29 12:53:29,724 -     => Main - Execução iniciada
2024-04-29 12:53:29,725 -     => commodities - Execução iniciada
2024-04-29 12:54:05,668 - DFI => Execução iniciada
2024-04-29 12:54:05,679 -     => Main - Execução iniciada
2024-04-29 12:54:05,680 -     => commodities - Execução iniciada
2024-04-29 12:57:19,967 -       => Error:       (X) exportDataframeToDatabase.py.[exportDataframeToDatabase]: Erro ao exportar informações para o(s) database(s) de Destino:: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]A instrução MERGE tentou um UPDATE ou DELETE na mesma linha mais de uma vez. Isso ocorre quando uma linha de destino corresponde a mais de uma linha de origem. Uma instrução MERGE não pode executar UPDATE/DELETE na mesma linha da tabela de destino várias vezes. Refine a cláusula ON para garantir que uma linha de destino corresponda, no máximo, a uma linha de origem ou use a cláusula GROUP BY para agrupar as linhas de origem. (8672) (SQLExecDirectW)')
[SQL: MERGE INTO MRV_Commodity_History AS target
        USING MRV_comhis_temp AS source
        ON target.comhis_date = source.comhis_date AND target.comhis_day_week = source.comhis_day_week AND target.comhis_commodity = source.comhis_commodity
        WHEN MATCHED THEN
            UPDATE SET target.comhis_date = source.comhis_date, target.comhis_day_week = source.comhis_day_week, target.comhis_commodity = source.comhis_commodity,
                target.comhis_SAP_product = source.comhis_SAP_product, target.comhis_price = source.comhis_price, target.comhis_indicator = source.comhis_indicator,
                target.comhis_unit_source = source.comhis_unit_source, target.comhis_unit_destiny = source.comhis_unit_destiny,
                target.comhis_conversion_factor = source.comhis_conversion_factor, target.comhis_price_unit = source.comhis_price_unit
        WHEN NOT MATCHED THEN
            INSERT (comhis_date, comhis_day_week, comhis_commodity, comhis_SAP_product, comhis_price, comhis_indicator, comhis_unit_source, comhis_unit_destiny,
                comhis_conversion_factor, comhis_price_unit) VALUES
                (source.comhis_date, source.comhis_day_week, source.comhis_commodity, source.comhis_SAP_product, source.comhis_price, source.comhis_indicator,
                source.comhis_unit_source, source.comhis_unit_destiny, source.comhis_conversion_factor, source.comhis_price_unit);
]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-04-29 12:59:02,324 - DFI => Execução iniciada
2024-04-29 12:59:02,348 -     => Main - Execução iniciada
2024-04-29 12:59:02,349 -     => commodities - Execução iniciada
2024-04-29 13:03:53,218 -       => Error:       (X) exportDataframeToDatabase.py.[exportDataframeToDatabase]: Erro ao exportar informações para o(s) database(s) de Destino:: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]A instrução MERGE tentou um UPDATE ou DELETE na mesma linha mais de uma vez. Isso ocorre quando uma linha de destino corresponde a mais de uma linha de origem. Uma instrução MERGE não pode executar UPDATE/DELETE na mesma linha da tabela de destino várias vezes. Refine a cláusula ON para garantir que uma linha de destino corresponda, no máximo, a uma linha de origem ou use a cláusula GROUP BY para agrupar as linhas de origem. (8672) (SQLExecDirectW)')
[SQL: MERGE INTO MRV_Commodity_History AS target
        USING MRV_comhis_temp AS source
        ON target.comhis_date = source.comhis_date AND target.comhis_day_week = source.comhis_day_week AND target.comhis_commodity = source.comhis_commodity
        WHEN MATCHED THEN
            UPDATE SET target.comhis_date = source.comhis_date, target.comhis_day_week = source.comhis_day_week, target.comhis_commodity = source.comhis_commodity,
                target.comhis_SAP_product = source.comhis_SAP_product, target.comhis_price = source.comhis_price, target.comhis_indicator = source.comhis_indicator,
                target.comhis_unit_source = source.comhis_unit_source, target.comhis_unit_destiny = source.comhis_unit_destiny,
                target.comhis_conversion_factor = source.comhis_conversion_factor, target.comhis_price_unit = source.comhis_price_unit
        WHEN NOT MATCHED THEN
            INSERT (comhis_date, comhis_day_week, comhis_commodity, comhis_SAP_product, comhis_price, comhis_indicator, comhis_unit_source, comhis_unit_destiny,
                comhis_conversion_factor, comhis_price_unit) VALUES
                (source.comhis_date, source.comhis_day_week, source.comhis_commodity, source.comhis_SAP_product, source.comhis_price, source.comhis_indicator,
                source.comhis_unit_source, source.comhis_unit_destiny, source.comhis_conversion_factor, source.comhis_price_unit);
]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-04-29 13:20:44,311 - DFI => Execução iniciada
2024-04-29 13:20:44,336 -     => Main - Execução iniciada
2024-04-29 13:20:44,337 -     => commodities - Execução iniciada
2024-04-29 13:25:05,068 -       => Error:       (X) exportDataframeToDatabase.py.[exportDataframeToDatabase]: Erro ao exportar informações para o(s) database(s) de Destino:: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]A instrução MERGE tentou um UPDATE ou DELETE na mesma linha mais de uma vez. Isso ocorre quando uma linha de destino corresponde a mais de uma linha de origem. Uma instrução MERGE não pode executar UPDATE/DELETE na mesma linha da tabela de destino várias vezes. Refine a cláusula ON para garantir que uma linha de destino corresponda, no máximo, a uma linha de origem ou use a cláusula GROUP BY para agrupar as linhas de origem. (8672) (SQLExecDirectW)')
[SQL: MERGE INTO MRV_Commodity_History AS target
        USING MRV_comhis_temp AS source
        ON target.comhis_date = source.comhis_date AND target.comhis_day_week = source.comhis_day_week AND target.comhis_commodity = source.comhis_commodity
        WHEN MATCHED THEN
            UPDATE SET target.comhis_date = source.comhis_date, target.comhis_day_week = source.comhis_day_week, target.comhis_commodity = source.comhis_commodity,
                target.comhis_SAP_product = source.comhis_SAP_product, target.comhis_price = source.comhis_price, target.comhis_indicator = source.comhis_indicator,
                target.comhis_unit_source = source.comhis_unit_source, target.comhis_unit_destiny = source.comhis_unit_destiny,
                target.comhis_conversion_factor = source.comhis_conversion_factor, target.comhis_price_unit = source.comhis_price_unit
        WHEN NOT MATCHED THEN
            INSERT (comhis_date, comhis_day_week, comhis_commodity, comhis_SAP_product, comhis_price, comhis_indicator, comhis_unit_source, comhis_unit_destiny,
                comhis_conversion_factor, comhis_price_unit) VALUES
                (source.comhis_date, source.comhis_day_week, source.comhis_commodity, source.comhis_SAP_product, source.comhis_price, source.comhis_indicator,
                source.comhis_unit_source, source.comhis_unit_destiny, source.comhis_conversion_factor, source.comhis_price_unit);
]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-04-29 13:25:44,260 - DFI => Execução iniciada
2024-04-29 13:25:44,287 -     => Main - Execução iniciada
2024-04-29 13:25:44,288 -     => commodities - Execução iniciada
2024-04-29 13:29:49,347 - DFI => Execução iniciada
2024-04-29 13:29:49,376 -     => Main - Execução iniciada
2024-04-29 13:29:49,377 -     => commodities - Execução iniciada
2024-04-29 13:33:13,001 - DFI => Execução iniciada
2024-04-29 13:33:13,029 -     => Main - Execução iniciada
2024-04-29 13:33:13,030 -     => commodities - Execução iniciada
2024-04-29 13:34:58,926 - DFI => Execução iniciada
2024-04-29 13:34:58,951 -     => Main - Execução iniciada
2024-04-29 13:34:58,952 -     => commodities - Execução iniciada
2024-04-29 13:39:45,979 - DFI => Execução iniciada
2024-04-29 13:39:46,004 -     => Main - Execução iniciada
2024-04-29 13:39:46,005 -     => commodities - Execução iniciada
2024-04-29 13:40:39,771 - DFI => Execução iniciada
2024-04-29 13:40:39,796 -     => Main - Execução iniciada
2024-04-29 13:40:39,797 -     => commodities - Execução iniciada
2024-04-29 13:41:33,595 - DFI => Execução iniciada
2024-04-29 13:41:33,622 -     => Main - Execução iniciada
2024-04-29 13:41:33,623 -     => commodities - Execução iniciada
2024-04-29 13:57:32,197 -       => Error:       (X) exportDataframeToDatabase.py.[exportDataframeToDatabase]: Erro ao exportar informações para o(s) database(s) de Destino:: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]A instrução MERGE tentou um UPDATE ou DELETE na mesma linha mais de uma vez. Isso ocorre quando uma linha de destino corresponde a mais de uma linha de origem. Uma instrução MERGE não pode executar UPDATE/DELETE na mesma linha da tabela de destino várias vezes. Refine a cláusula ON para garantir que uma linha de destino corresponda, no máximo, a uma linha de origem ou use a cláusula GROUP BY para agrupar as linhas de origem. (8672) (SQLExecDirectW)')
[SQL: MERGE INTO MRV_Commodity_History AS target
        USING MRV_comhis_temp AS source
        ON target.comhis_date = source.comhis_date AND target.comhis_day_week = source.comhis_day_week AND target.comhis_commodity = source.comhis_commodity
        WHEN MATCHED THEN
            UPDATE SET target.comhis_date = source.comhis_date, target.comhis_day_week = source.comhis_day_week, target.comhis_commodity = source.comhis_commodity,
                target.comhis_SAP_product = source.comhis_SAP_product, target.comhis_price = source.comhis_price, target.comhis_indicator = source.comhis_indicator,
                target.comhis_unit_source = source.comhis_unit_source, target.comhis_unit_destiny = source.comhis_unit_destiny,
                target.comhis_conversion_factor = source.comhis_conversion_factor, target.comhis_price_unit = source.comhis_price_unit
        WHEN NOT MATCHED THEN
            INSERT (comhis_date, comhis_day_week, comhis_commodity, comhis_SAP_product, comhis_price, comhis_indicator, comhis_unit_source, comhis_unit_destiny,
                comhis_conversion_factor, comhis_price_unit) VALUES
                (source.comhis_date, source.comhis_day_week, source.comhis_commodity, source.comhis_SAP_product, source.comhis_price, source.comhis_indicator,
                source.comhis_unit_source, source.comhis_unit_destiny, source.comhis_conversion_factor, source.comhis_price_unit);
]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-04-29 14:03:19,280 - DFI => Execução iniciada
2024-04-29 14:03:19,304 -     => Main - Execução iniciada
2024-04-29 14:03:19,305 -     => commodities - Execução iniciada
2024-04-29 14:15:46,370 - DFI => Execução iniciada
2024-04-29 14:15:46,395 -     => Main - Execução iniciada
2024-04-29 14:15:46,396 -     => commodities - Execução iniciada
2024-04-29 14:15:53,340 - DFI => Execução iniciada
2024-04-29 14:15:53,365 -     => Main - Execução iniciada
2024-04-29 14:15:53,366 -     => commodities - Execução iniciada
2024-04-29 14:21:14,519 - DFI => Execução iniciada
2024-04-29 14:21:14,544 -     => Main - Execução iniciada
2024-04-29 14:21:14,545 -     => commodities - Execução iniciada
2024-04-29 14:24:06,197 - DFI => Execução iniciada
2024-04-29 14:24:06,204 -     => Main - Execução iniciada
2024-04-29 14:24:06,205 -     => commodities - Execução iniciada
2024-04-29 14:24:43,368 -     => commodities - Execução concluída
2024-04-29 14:24:43,385 -     => avacorp - Execução iniciada
2024-04-29 14:25:15,741 - DFI => Execução iniciada
2024-04-29 14:25:15,768 -     => Main - Execução iniciada
2024-04-29 14:25:15,769 -     => commodities - Execução iniciada
2024-04-29 14:25:41,339 -       => Error:       (X) updateDataframe.py.[updateDataframe]: Update dos dataframes:: 'comhis_commodity'
2024-04-29 14:26:15,139 - DFI => Execução iniciada
2024-04-29 14:26:15,167 -     => Main - Execução iniciada
2024-04-29 14:26:15,168 -     => commodities - Execução iniciada
2024-04-29 14:27:07,129 - DFI => Execução iniciada
2024-04-29 14:27:07,155 -     => Main - Execução iniciada
2024-04-29 14:27:07,156 -     => commodities - Execução iniciada
2024-04-29 14:27:43,627 - DFI => Execução iniciada
2024-04-29 14:27:43,653 -     => Main - Execução iniciada
2024-04-29 14:27:43,653 -     => commodities - Execução iniciada
2024-04-29 14:29:10,577 - DFI => Execução iniciada
2024-04-29 14:29:10,601 -     => Main - Execução iniciada
2024-04-29 14:29:10,602 -     => commodities - Execução iniciada
2024-04-29 14:53:43,856 - DFI => Execução iniciada
2024-04-29 14:53:43,882 -     => Main - Execução iniciada
2024-04-29 14:53:43,882 -     => commodities - Execução iniciada
2024-04-29 15:00:28,707 - DFI => Execução iniciada
2024-04-29 15:00:28,716 -     => Main - Execução iniciada
2024-04-29 15:00:28,716 -     => commodities - Execução iniciada
2024-04-29 15:01:03,833 -     => commodities - Execução concluída
2024-04-29 15:01:03,847 -     => avacorp - Execução iniciada
2024-04-29 15:02:28,304 -     => avacorp - Execução concluída
2024-04-29 15:02:28,316 -     => balancasp6000 - Execução iniciada
2024-04-29 15:02:28,725 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 15:02:28,766 -     => balancasp6000 - Execução concluída
2024-04-29 15:02:28,766 -     => Main - Execução concluída
2024-04-29 15:02:48,557 - DFI => Execução iniciada
2024-04-29 15:02:48,566 -     => Main - Execução iniciada
2024-04-29 15:02:48,566 -     => commodities - Execução iniciada
2024-04-29 15:03:23,604 -     => commodities - Execução concluída
2024-04-29 15:03:23,617 -     => avacorp - Execução iniciada
2024-04-29 15:14:44,564 - DFI => Execução iniciada
2024-04-29 15:14:44,572 -     => Main - Execução iniciada
2024-04-29 15:14:44,572 -     => commodities - Execução iniciada
2024-04-29 15:15:19,426 -     => commodities - Execução concluída
2024-04-29 15:15:19,439 -     => avacorp - Execução iniciada
2024-04-29 15:16:23,034 -     => avacorp - Execução concluída
2024-04-29 15:16:23,045 -     => balancasp6000 - Execução iniciada
2024-04-29 15:16:23,317 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 15:16:23,356 -     => balancasp6000 - Execução concluída
2024-04-29 15:16:23,356 -     => Main - Execução concluída
2024-04-29 15:19:55,255 - DFI => Execução iniciada
2024-04-29 15:19:55,264 -     => Main - Execução iniciada
2024-04-29 15:19:55,265 -     => commodities - Execução iniciada
2024-04-29 15:20:45,429 -     => commodities - Execução concluída
2024-04-29 15:20:45,443 -     => avacorp - Execução iniciada
2024-04-29 15:21:53,994 -     => avacorp - Execução concluída
2024-04-29 15:21:54,006 -     => balancasp6000 - Execução iniciada
2024-04-29 15:21:54,274 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 15:21:54,309 -     => balancasp6000 - Execução concluída
2024-04-29 15:21:54,309 -     => Main - Execução concluída
2024-04-29 15:23:02,990 - DFI => Execução iniciada
2024-04-29 15:23:03,017 -     => Main - Execução iniciada
2024-04-29 15:23:03,018 -     => commodities - Execução iniciada
2024-04-29 15:26:47,110 - DFI => Execução iniciada
2024-04-29 15:26:47,119 -     => Main - Execução iniciada
2024-04-29 15:26:47,119 -     => commodities - Execução iniciada
2024-04-29 15:27:24,552 -     => commodities - Execução concluída
2024-04-29 15:27:24,565 -     => avacorp - Execução iniciada
2024-04-29 15:28:29,103 -     => avacorp - Execução concluída
2024-04-29 15:28:29,114 -     => balancasp6000 - Execução iniciada
2024-04-29 15:28:29,379 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 15:29:47,607 - DFI => Execução iniciada
2024-04-29 15:29:47,632 -     => Main - Execução iniciada
2024-04-29 15:29:47,633 -     => commodities - Execução iniciada
2024-04-29 15:34:40,412 - DFI => Execução iniciada
2024-04-29 15:34:40,420 -     => Main - Execução iniciada
2024-04-29 15:34:40,420 -     => commodities - Execução iniciada
2024-04-29 15:35:15,801 -     => commodities - Execução concluída
2024-04-29 15:35:15,816 -     => avacorp - Execução iniciada
2024-04-29 15:38:31,241 - DFI => Execução iniciada
2024-04-29 15:38:31,248 -     => Main - Execução iniciada
2024-04-29 15:38:31,249 -     => commodities - Execução iniciada
2024-04-29 15:38:35,167 -       => Error:       (X) exportDataframeToDatabase.py.[exportDataframeToDatabase]: Erro ao exportar informações para o(s) database(s) de Destino:: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2024-04-29 15:39:40,135 - DFI => Execução iniciada
2024-04-29 15:39:40,142 -     => Main - Execução iniciada
2024-04-29 15:39:40,143 -     => commodities - Execução iniciada
2024-04-29 15:40:14,302 -     => commodities - Execução concluída
2024-04-29 15:40:14,315 -     => avacorp - Execução iniciada
2024-04-29 15:41:19,345 -     => avacorp - Execução concluída
2024-04-29 15:41:19,357 -     => balancasp6000 - Execução iniciada
2024-04-29 15:41:19,608 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 15:41:19,642 -     => balancasp6000 - Execução concluída
2024-04-29 15:41:19,642 -     => Main - Execução concluída
2024-04-29 15:42:42,449 - DFI => Execução iniciada
2024-04-29 15:42:42,483 -     => Main - Execução iniciada
2024-04-29 15:42:42,484 -     => balancasp6000 - Execução iniciada
2024-04-29 15:44:52,391 - DFI => Execução iniciada
2024-04-29 15:44:52,416 -     => Main - Execução iniciada
2024-04-29 15:44:52,417 -     => balancasp6000 - Execução iniciada
2024-04-29 15:46:13,000 - DFI => Execução iniciada
2024-04-29 15:46:13,027 -     => Main - Execução iniciada
2024-04-29 15:46:13,028 -     => balancasp6000 - Execução iniciada
2024-04-29 15:47:25,082 -       => Error:       (X) updateDataframe.py.[updateDataframe]: Update dos dataframes:: "None of ['comhis_date', 'comhis_day_week', 'comhis_commodity'] are in the columns"
2024-04-29 15:48:02,795 - DFI => Execução iniciada
2024-04-29 15:48:02,823 -     => Main - Execução iniciada
2024-04-29 15:48:02,824 -     => balancasp6000 - Execução iniciada
2024-04-29 15:48:49,989 - DFI => Execução iniciada
2024-04-29 15:48:50,001 -     => Main - Execução iniciada
2024-04-29 15:48:50,002 -     => commodities - Execução iniciada
2024-04-29 15:49:30,979 -     => commodities - Execução concluída
2024-04-29 15:49:30,993 -     => avacorp - Execução iniciada
2024-04-29 15:50:34,866 -     => avacorp - Execução concluída
2024-04-29 15:50:34,878 -     => balancasp6000 - Execução iniciada
2024-04-29 15:50:35,208 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 15:50:35,231 -     => balancasp6000 - Execução concluída
2024-04-29 15:50:35,231 -     => Main - Execução concluída
2024-04-29 15:52:35,301 -     => Main - Execução iniciada
2024-04-29 15:52:35,301 -     => commodities - Execução iniciada
2024-04-29 15:53:10,249 -     => commodities - Execução concluída
2024-04-29 15:53:10,262 -     => avacorp - Execução iniciada
2024-04-29 15:54:15,508 -     => avacorp - Execução concluída
2024-04-29 15:54:15,519 -     => balancasp6000 - Execução iniciada
2024-04-29 15:54:15,616 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 15:54:15,645 -     => balancasp6000 - Execução concluída
2024-04-29 15:54:15,645 -     => Main - Execução concluída
2024-04-29 15:56:15,718 -     => Main - Execução iniciada
2024-04-29 15:56:15,718 -     => commodities - Execução iniciada
2024-04-29 15:56:50,807 -     => commodities - Execução concluída
2024-04-29 15:56:50,821 -     => avacorp - Execução iniciada
2024-04-29 15:57:56,526 -     => avacorp - Execução concluída
2024-04-29 15:57:56,536 -     => balancasp6000 - Execução iniciada
2024-04-29 15:57:56,796 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 15:57:56,905 -     => balancasp6000 - Execução concluída
2024-04-29 15:57:56,905 -     => Main - Execução concluída
2024-04-29 15:59:56,971 -     => Main - Execução iniciada
2024-04-29 15:59:56,971 -     => commodities - Execução iniciada
2024-04-29 16:00:00,428 -       => Error:       (X) exportDataframeToDatabase.py.[exportDataframeToDatabase]: Erro ao exportar informações para o(s) database(s) de Destino:: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2024-04-29 16:00:12,744 - DFI => Execução iniciada
2024-04-29 16:00:12,757 -     => Main - Execução iniciada
2024-04-29 16:00:12,757 -     => balancasp6000 - Execução iniciada
2024-04-29 16:00:13,085 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 16:00:13,115 -     => balancasp6000 - Execução concluída
2024-04-29 16:00:13,116 -     => Main - Execução concluída
2024-04-29 16:00:34,611 - DFI => Execução iniciada
2024-04-29 16:00:34,638 -     => Main - Execução iniciada
2024-04-29 16:00:34,639 -     => balancasp6000 - Execução iniciada
2024-04-29 16:02:12,196 - DFI => Execução iniciada
2024-04-29 16:02:12,203 -     => Main - Execução iniciada
2024-04-29 16:02:12,204 -     => balancasp6000 - Execução iniciada
2024-04-29 16:02:12,569 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-04-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-04-29 16:02:12,596 -     => balancasp6000 - Execução concluída
2024-04-29 16:02:12,596 -     => Main - Execução concluída
